apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ingress-nginx-demo
    server: 'https://kubernetes.default.svc'
  source:
    path: ingress-nginx-demo
    repoURL: 'https://github.com/ahmetceyhan/multi_ingress_controller_argocd_helm_chart.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: ingress-nginx-demo-project