apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault-demo
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: vault
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'